# Generated by Django 4.1.2 on 2022-12-08 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(blank=True, help_text='Type username here', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, default='', help_text='Type password here', max_length=20)),
                ('first_name', models.CharField(blank=True, default='', help_text='Type first name here', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', help_text='Type last name here', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Type email here', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
