# Generated by Django 4.1.2 on 2022-12-09 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Brick', 'Brick'), ('Technic', 'Technic'), ('Electric', 'Electric')], help_text='Select category', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Decorated', 'Decorated'), ('Modified', 'Modified'), ('Promotional', 'Promotional'), ('Round', 'Round'), ('Axle', 'Axle'), ('Brick', 'Brick'), ('Connector', 'Connector'), ('Disk', 'Disk'), ('Gear', 'Gear'), ('Battery box', 'Battery box'), ('Programmable', 'Programmable'), ('Lights', 'Lights'), ('Motor', 'Motor'), ('Wire', 'Wire')], help_text='Select subcategory', max_length=50, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='LegoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type part name', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Type part description (up to 1000 characters)', max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('public_access', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.subcategory')),
            ],
        ),
    ]
