# Generated by Django 4.1.3 on 2022-11-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='legopart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='legopart',
            name='description',
            field=models.TextField(blank=True, help_text='Type part description (up to 1000 characters)', max_length=1000),
        ),
        migrations.AddField(
            model_name='legopart',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='legopart',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legopart',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Type email here', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Boole', help_text='Type last name here', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', help_text='Type password here', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', help_text='Type username here', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default='gbViNj8fXfem3BKcbT5dqk', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('B', 'Brick'), ('T', 'Technic'), ('E', 'Electric')], help_text='Select category', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='legopart',
            name='id',
            field=models.UUIDField(default='mNkwyQgBkarZpAxuQ78R2o', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legopart',
            name='name',
            field=models.CharField(help_text='Type part name', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.CharField(default='2m96s9Z2HbLciMJ6koNNjr', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Select subcategory', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='George', help_text='Type first name here', max_length=50),
        ),
    ]
