# Generated by Django 4.1.2 on 2022-11-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Brick', 'Brick'), ('Technic', 'Technic'), ('Electric', 'Electric')], help_text='Select category', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(choices=[('Decorated', 'Decorated'), ('Modified', 'Modified'), ('Promotional', 'Promotional'), ('Round', 'Round'), ('Axle', 'Axle'), ('Brick', 'Brick'), ('Connector', 'Connector'), ('Disk', 'Disk'), ('Gear', 'Gear'), ('Battery box', 'Battery box'), ('Programmable', 'Programmable'), ('Lights', 'Lights'), ('Motor', 'Motor'), ('Wire', 'Wire')], help_text='Select subcategory', max_length=50, unique=True),
        ),
    ]
