# Generated by Django 4.1.2 on 2022-11-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_user_user_image_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Type email here', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', help_text='Type username here', max_length=30, primary_key=True, serialize=False),
        ),
    ]
