# Generated by Django 4.1.3 on 2022-11-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(choices=[('Brick', 'Brick'), ('Technic', 'Technic'), ('Electric', 'Electric')], null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
    ]
