# Generated by Django 4.1.2 on 2022-12-07 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_legopart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Brick', 'Brick'), ('Technic', 'Technic'), ('Electric', 'Electric')], help_text='Select category', max_length=50, primary_key=True, serialize=False),
        ),
    ]
